plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id("org.jetbrains.kotlin.plugin.compose") version "2.2.21"
}

android {
    namespace 'com.example.tieniiltempo'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.tieniiltempo"
        minSdk 27
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildFeatures { compose true }
    composeOptions { kotlinCompilerExtensionVersion = "1.5.15" }
    kotlinOptions { jvmTarget = '1.8' }

    composeCompiler {
        enableStrongSkippingMode = true
    }
}

dependencies {

    // COMPOSE
    implementation(platform(libs.androidx.compose.bom.v20240401))

    implementation(libs.material3)
    implementation(libs.androidx.compose.material)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.ui.tooling.preview.v173)
    implementation libs.androidx.compose.foundation
    debugImplementation(libs.androidx.compose.ui.tooling.v173)


    // FIREBASE
    implementation(platform("com.google.firebase:firebase-bom:33.1.2"))
    implementation("com.google.firebase:firebase-auth-ktx")
    implementation("com.google.firebase:firebase-firestore-ktx")
    implementation("com.google.firebase:firebase-storage-ktx")
    implementation("com.google.firebase:firebase-messaging-ktx")


    // ANDROIDX
    implementation(libs.androidx.core.ktx.v1131)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity.compose.v192)
    implementation(libs.androidx.lifecycle.runtime.ktx.v294)
    implementation(libs.androidx.compose.ui.text)
    implementation(libs.androidx.compose.ui.v173)
    implementation(libs.androidx.compose.material3.v130)


    // NAVIGATION + COROUTINES
    implementation(libs.androidx.navigation.compose)
    implementation(libs.kotlinx.coroutines.play.services)


    // COIL
    implementation(libs.coil.compose)


    // PLAY SERVICES (location)
    implementation(libs.play.services.location)
}